---
- hosts: 18.220.153.191
  tasks:
   - name: Install Apache
     apt: pkg=apache2 state=installed update_cache=true
     notify:
      - Start apache

  handlers:
   - name: Start apache
     service: name=apache2 state=started
